from __future__ import annotations

from enum import Enum
from typing import Any, Callable

from core.observability.events import DebugEvent, EventBus


class AIEventType(str, Enum):
    TOOL_EXECUTED = "TOOL_EXECUTED"
    TASK_FAILED = "TASK_FAILED"
    TASK_STARTED = "TASK_STARTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    MEMORY_UPDATED = "MEMORY_UPDATED"
    ACTIVE_WINDOW_CHANGED = "ACTIVE_WINDOW_CHANGED"
    DEPENDENCY_MISSING = "DEPENDENCY_MISSING"
    USER_IDLE = "USER_IDLE"
    AGENT_COMPLETED = "AGENT_COMPLETED"
    CONTEXT_UPDATED = "CONTEXT_UPDATED"
    SUGGESTION_CREATED = "SUGGESTION_CREATED"
    SANDBOX_VIOLATION = "SANDBOX_VIOLATION"
    TASK_CANCELLED = "TASK_CANCELLED"
    TASK_RETRY = "TASK_RETRY"
    WORKER_REGISTERED = "WORKER_REGISTERED"
    WORKER_HEARTBEAT = "WORKER_HEARTBEAT"
    DISTRIBUTED_TASK_QUEUED = "DISTRIBUTED_TASK_QUEUED"
    DISTRIBUTED_TASK_ASSIGNED = "DISTRIBUTED_TASK_ASSIGNED"
    RUNTIME_SELECTED = "RUNTIME_SELECTED"
    RUNTIME_FAILED = "RUNTIME_FAILED"
    AGENT_SPAWNED = "AGENT_SPAWNED"
    SKILL_VALIDATED = "SKILL_VALIDATED"
    INCIDENT_CREATED = "INCIDENT_CREATED"
    PLUGIN_VERIFIED = "PLUGIN_VERIFIED"
    WORKFLOW_STARTED = "WORKFLOW_STARTED"
    WORKFLOW_COMPLETED = "WORKFLOW_COMPLETED"
    SECURITY_DECISION = "SECURITY_DECISION"
    MULTIMODAL_CONTEXT_UPDATED = "MULTIMODAL_CONTEXT_UPDATED"
    VISION_SCREEN_PARSED = "VISION_SCREEN_PARSED"
    LONG_TASK_CHECKPOINTED = "LONG_TASK_CHECKPOINTED"
    REASONING_PROFILE_SELECTED = "REASONING_PROFILE_SELECTED"
    ENVIRONMENT_SNAPSHOT = "ENVIRONMENT_SNAPSHOT"
    SUPERVISOR_ALERT = "SUPERVISOR_ALERT"
    INTERACTION_DECISION = "INTERACTION_DECISION"
    REALTIME_UPDATE = "REALTIME_UPDATE"
    KNOWLEDGE_LINKED = "KNOWLEDGE_LINKED"
    WORKSPACE_RESTORED = "WORKSPACE_RESTORED"
    EXECUTION_GRAPH_UPDATED = "EXECUTION_GRAPH_UPDATED"
    OPTIMIZATION_DECISION = "OPTIMIZATION_DECISION"
    AUTOMATION_PREVIEWED = "AUTOMATION_PREVIEWED"
    AI_SHELL_PLAN_CREATED = "AI_SHELL_PLAN_CREATED"
    DEV_PLATFORM_ANALYSIS = "DEV_PLATFORM_ANALYSIS"
    PERSONALIZATION_UPDATED = "PERSONALIZATION_UPDATED"
    SAFETY_CHECKPOINT = "SAFETY_CHECKPOINT"
    FEDERATED_NODE_SYNCED = "FEDERATED_NODE_SYNCED"
    SEMANTIC_OS_UPDATED = "SEMANTIC_OS_UPDATED"
    COGNITIVE_ORCHESTRATION_UPDATED = "COGNITIVE_ORCHESTRATION_UPDATED"
    ECOSYSTEM_COORDINATED = "ECOSYSTEM_COORDINATED"
    TIMELINE_RECORDED = "TIMELINE_RECORDED"
    COLLABORATION_AI_DECISION = "COLLABORATION_AI_DECISION"
    GOVERNANCE_DECISION = "GOVERNANCE_DECISION"
    SEMANTIC_GRAPH_UPDATED = "SEMANTIC_GRAPH_UPDATED"
    WORKFLOW_INTELLIGENCE_UPDATED = "WORKFLOW_INTELLIGENCE_UPDATED"
    RUNTIME_ECONOMICS_DECISION = "RUNTIME_ECONOMICS_DECISION"
    CONTEXT_SYNC_DECISION = "CONTEXT_SYNC_DECISION"
    STATE_SNAPSHOT_CREATED = "STATE_SNAPSHOT_CREATED"
    AUTONOMY_BOUNDARY_DECISION = "AUTONOMY_BOUNDARY_DECISION"
    INTERACTION_FABRIC_DECISION = "INTERACTION_FABRIC_DECISION"
    DEV_ECOSYSTEM_ANALYSIS = "DEV_ECOSYSTEM_ANALYSIS"
    ANALYTICS_RECORDED = "ANALYTICS_RECORDED"
    TRANSPARENCY_NARRATIVE_CREATED = "TRANSPARENCY_NARRATIVE_CREATED"
    SELF_OPTIMIZATION_PROPOSED = "SELF_OPTIMIZATION_PROPOSED"
    META_ORCHESTRATION_UPDATED = "META_ORCHESTRATION_UPDATED"
    TOPOLOGY_UPDATED = "TOPOLOGY_UPDATED"
    DISTRIBUTED_MEMORY_SYNCED = "DISTRIBUTED_MEMORY_SYNCED"
    COGNITIVE_EXECUTION_PLANNED = "COGNITIVE_EXECUTION_PLANNED"
    TRUSTED_AUTONOMY_DECISION = "TRUSTED_AUTONOMY_DECISION"
    POLICY_EVALUATED = "POLICY_EVALUATED"
    OPERATING_FABRIC_EVENT = "OPERATING_FABRIC_EVENT"
    RESILIENCE_DECISION = "RESILIENCE_DECISION"
    RESOURCE_ECONOMY_DECISION = "RESOURCE_ECONOMY_DECISION"
    SEMANTIC_WORKFLOW_UPDATED = "SEMANTIC_WORKFLOW_UPDATED"
    INTERFACE_LAYER_SYNCED = "INTERFACE_LAYER_SYNCED"
    RUNTIME_VIRTUALIZED = "RUNTIME_VIRTUALIZED"
    SELF_OBSERVATION_REPORTED = "SELF_OBSERVATION_REPORTED"
    SEMANTIC_ANALYTICS_RECORDED = "SEMANTIC_ANALYTICS_RECORDED"
    SECURITY_FABRIC_DECISION = "SECURITY_FABRIC_DECISION"
    HUMAN_GOVERNANCE_DECISION = "HUMAN_GOVERNANCE_DECISION"
    ECOSYSTEM_SDK_VALIDATED = "ECOSYSTEM_SDK_VALIDATED"
    OPS_CENTER_SNAPSHOT_CREATED = "OPS_CENTER_SNAPSHOT_CREATED"
    DISTRIBUTED_OS_UPDATED = "DISTRIBUTED_OS_UPDATED"
    FEDERATION_DECISION = "FEDERATION_DECISION"
    SEMANTIC_NETWORK_ROUTED = "SEMANTIC_NETWORK_ROUTED"
    DISTRIBUTED_COGNITION_UPDATED = "DISTRIBUTED_COGNITION_UPDATED"
    NODE_RUNTIME_UPDATED = "NODE_RUNTIME_UPDATED"
    SERVICE_MESH_ROUTED = "SERVICE_MESH_ROUTED"
    GLOBAL_CONTEXT_SYNCED = "GLOBAL_CONTEXT_SYNCED"
    MEMORY_GOVERNANCE_DECISION = "MEMORY_GOVERNANCE_DECISION"
    TOPOLOGY_INTELLIGENCE_REPORTED = "TOPOLOGY_INTELLIGENCE_REPORTED"
    CLOUD_EDGE_DECISION = "CLOUD_EDGE_DECISION"
    DISTRIBUTED_SECURITY_DECISION = "DISTRIBUTED_SECURITY_DECISION"
    ECOSYSTEM_REGISTRY_UPDATED = "ECOSYSTEM_REGISTRY_UPDATED"
    RESOURCE_ORCHESTRATION_DECISION = "RESOURCE_ORCHESTRATION_DECISION"
    DISTRIBUTED_OBSERVABILITY_RECORDED = "DISTRIBUTED_OBSERVABILITY_RECORDED"
    DISASTER_RECOVERY_DECISION = "DISASTER_RECOVERY_DECISION"
    DISTRIBUTED_GOVERNANCE_DECISION = "DISTRIBUTED_GOVERNANCE_DECISION"
    DISTRIBUTED_DEV_PLATFORM_VALIDATED = "DISTRIBUTED_DEV_PLATFORM_VALIDATED"
    COMMAND_CENTER_SNAPSHOT_CREATED = "COMMAND_CENTER_SNAPSHOT_CREATED"
    API_CONTRACT_VALIDATED = "API_CONTRACT_VALIDATED"
    API_AUTH_DECISION = "API_AUTH_DECISION"
    CLOUD_READINESS_REPORTED = "CLOUD_READINESS_REPORTED"
    CLOUD_SYNC_PLANNED = "CLOUD_SYNC_PLANNED"
    CLOUD_STORAGE_DECISION = "CLOUD_STORAGE_DECISION"
    PLATFORM_EXTENSION_VALIDATED = "PLATFORM_EXTENSION_VALIDATED"
    AGENT_ECOSYSTEM_VALIDATED = "AGENT_ECOSYSTEM_VALIDATED"
    AGENT_ORCHESTRATION_PLANNED = "AGENT_ORCHESTRATION_PLANNED"
    AGENT_MEMORY_BOUND = "AGENT_MEMORY_BOUND"
    AUTOMATION_TEMPLATE_VALIDATED = "AUTOMATION_TEMPLATE_VALIDATED"
    MARKETPLACE_PACKAGE_EVALUATED = "MARKETPLACE_PACKAGE_EVALUATED"


def _event_name(event_type: AIEventType | str) -> str:
    value = event_type.value if isinstance(event_type, AIEventType) else str(event_type)
    return f"ai.{value}"


def publish_event(
    event_type: AIEventType | str,
    payload: dict[str, Any] | None = None,
    *,
    source: str = "core",
    trace_id: str = "",
) -> DebugEvent:
    return EventBus.get().emit(_event_name(event_type), source, dict(payload or {}), trace_id=trace_id)


def subscribe(callback: Callable[[DebugEvent], None]) -> None:
    EventBus.get().subscribe(callback)


def replay_events(*, event_type: AIEventType | str | None = None, since_ts: float = 0.0, limit: int = 500) -> list[dict[str, Any]]:
    event_types = [_event_name(event_type)] if event_type else None
    return EventBus.get().replay(event_types=event_types, since_ts=since_ts, limit=limit)
